### ISSUE TITLE
Date type attribute

### ISSUE THREAD

**Issue by aphroz** [algolia/algoliasearch-magento#164] opened 2015-07-30 14:30 UTC
It would be nice to have a date facet type with a calendar

**Comment by maxiloc** [comment] 2015-07-30 14:32
@aphroz What is your use case ?

**Comment by aphroz** [comment] 2015-07-30 14:32
I am trying to sort by creation date

**Comment by maxiloc** [comment] 2015-07-30 14:36
Sorting on date is already possible and does not require facets.

If you want a facet yes you will need a new facet type.

Do you have an idea how you want it to be displayed ?

**Comment by aphroz** [comment] 2015-07-30 14:48
You mean by creating an index? I would need not only to sort by date but also to select a specific date range.

I imagine that a good solution would be to use a calendar like in the magento advanced search:

![image](https://cloud.githubusercontent.com/assets/261406/8986082/c01b185a-36da-11e5-97d3-34f7d68aa790.png)

**Comment by maxiloc** [comment] 2015-07-30 15:50
@aphroz Ok will see what we can do about that

**Comment by maxiloc** [comment] 2015-08-20 11:49
We are working on an instansearch.js library, and waiting for it to be available to develop the date facet as a widget.

**Comment by maxiloc** [comment] 2015-09-21 15:31
Duplicate of #206

**Closed by maxiloc** 2015-09-21 15:31 UTC
Labels: feature, instantsearch.js, minor
