### ISSUE TITLE
Indices ordered_qty=0 and stock_qty=0 for configurable products

### ISSUE THREAD

**Issue by webtekindo** [algolia/algoliasearch-magento#834] opened 2017-05-22 03:22 UTC
Hello,

Our website use 90% of configurable products, and we notice in the product indices that ordered_qty and stock_qty are 0 for all our configurable. Our first attribute for ranking is ordered_qty which make sense but because of that problem we get some weird result like a simple product very low on sale on top of a configurable that we sell 1000s times.

I believe that's a big issue for a lot of us.

Is there someway to fix that?

Thanks.

**Comment by JanPetr** [comment] 2017-05-22 09:36
Hello @webtekindo,

I just checked and I'm not able to reproduce. Which version of Magento do you use?
The extension [gets the `ordered_qty` directly from Product object](https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php#L857). Can you dive into a code there and see why it fetches 0 for you?

Thanks!

**Comment by webtekindo** [comment] 2017-05-22 12:36
Hi @JanPetr ,

I check the code and the [ordered_qty is set in Helper/Data](https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/Helper/Data.php#L521).

I believe the problem is because we use the very popular extension [Simple Configurable Product](https://www.magentocommerce.com/magento-connect/simple-configurable-products.html). The product add to cart is not the configurable product (with configured option) but the simple product. And in that case the join on the configurable entity_id will return nothing for ordered_qty.

Is this something that you can fix?

Thanks.

**Comment by damcou** [comment] 2018-08-27 13:25
hi @webtekindo ,

Hi, I don't know if you have still the issue. I'll close this ticket but feel free to reopen it if you're still experiencing it.

**Closed by damcou** 2018-08-27 13:25 UTC
