### ISSUE TITLE
Product search url adding indexer.php after enable the cron tab

### ISSUE THREAD

**Issue by vijaymagento1** [algolia/algoliasearch-magento#965] opened 2017-11-10 08:41 UTC
Hi Algolia support team,

We have installed and configured **"algolia search 1.12.0"** module on the latest magento(1.9.3.6) and we have enabled Indexing Queue/cron and added queue cron tab **(*/5 * * * * php -f /absolute/path/to/magento/shell/indexer.php -- -reindex algolia_queue_runner)** on the server. After process indexing queue/cron, when we search the product on the frontend it's adding indexer.php on the product url. 

Please review the issues ASAP and let us know solution, why Indexing Queue/cron adding indexer.php on the some of the product urls?

Thanks!

**Comment by JanPetr** [comment] 2017-11-13 13:49
Hello Vijay,

I just tested and I'm not able to reproduce. What version of Magento do you use?

**Comment by vijaymagento1** [comment] 2017-11-13 13:53
Hi Jan,
I am using latest magento community version (1.9.3.6).

Thanks!

**Comment by hyteckit** [comment] 2017-11-19 21:25
I have the same issue. Not just for product URLs, but category URLs too.

Temporary fix is to turn on "Use Web Server Rewrites" under General > Web > Search Engine Optimization.

**Comment by vijaymagento1** [comment] 2017-11-20 08:55
Hi hyteckit,
Thanks for the updates.

**Comment by JanPetr** [comment] 2017-11-20 11:40
Hello @vijaymagento1 and @hyteckit,

thanks for bringing this up. 
Yes, the extension takes URLs from Magento and doesn't compose it on it's own. And Magento respects the configuration settings.
I don't think it's a good idea to override this behavior in the extension. So I'll add a notice to documentation and close this issue.

Thanks for your inputs! 💯

**Closed by JanPetr** 2017-11-20 11:40 UTC

**Comment by hyteckit** [comment] 2017-11-20 20:31
JanPetr,

You are closing the case without fixing the BUG?

What you've said it's not true. algoliasearch-magento does compose its own URL and stores the absolute path into the algolia database. It just does it incorrectly by relying on $product->getProductUrl() function.

Anyway. Here's my fix. Under file "Algolia>Algoliasearch>Helper>Entity>Producthelper.php"

Change getProductUrl() to getRequestPath(). That'll give you the relative path instead of the incorrect absolute path.

```
        $customData = array(
            'objectID'           => $product->getId(),
            'name'               => $product->getName(),
            'url'                => $product->**getProductUrl**(),
            'visibility_search'  => (int) (in_array($visibility, $visibleInSearch)),
            'visibility_catalog' => (int) (in_array($visibility, $visibleInCatalog)),
        );
```

```
        $customData = array(
            'objectID'           => $product->getId(),
            'name'               => $product->getName(),
            'url'                => $product->**getRequestPath**(),
            'visibility_search'  => (int) (in_array($visibility, $visibleInSearch)),
            'visibility_catalog' => (int) (in_array($visibility, $visibleInCatalog)),
        );


```

**Comment by hyteckit** [comment] 2017-11-20 22:16
Okay. I figure out how to recreate the BUG.

If you have "Use Web Server Rewrites" turned off.

If you run "Algolia Search Queue Runner" from Index Management, the product URLs is correct with 'index.php' in the URL.

If you run it from the command line "php -f ./indexer.php -- -reindex algolia_queue_runner", then the product URLs is NOT correct with 'indexer.php' in the URL.

That's because the function $product->getProductUrl() gets the URL from the script URL which is indexer.php when you run it from the command line.
