### ISSUE TITLE
Autocomplete not working on Internet Explorer 11

### ISSUE THREAD

**Issue by alicef907** [algolia/algoliasearch-magento#1057] opened 2018-09-18 23:06 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**Bug: What is the current behavior?**

Autocomplete search results not appearing on Internet Explorer 11 after update from 1.13.0 to 1.14.0, not sure if this worked on v 1.13.0. Please contact me for the URL of the website this is occurring on.

**Bug: What is the expected behavior?**

Autocomplete search results should appear when you enter a search string.

**Bug: What is the proposed solution?**

Unsure, looks like a JS issue, no obvious errors appear at the console though.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**

Algolia 1.14.0, Magento 1.9.2.4

Website is https://www.retravision.com.au/

**Comment by JanPetr** [comment] 2019-02-14 10:43
Duplicate of #1037

**Closed by JanPetr** 2019-02-14 10:43 UTC
