### ISSUE TITLE
1.14 & 1.15 "Algolia Search - Remove inactive products from Algolia" Index Management is not showing

### ISSUE THREAD

**Issue by tomekjordan** [algolia/algoliasearch-magento#1106] opened 2019-02-16 15:08 UTC
**Do you want to request a *feature* or report a *bug*?**

BUG

**Bug: What is the current behavior?**
Last indexer Algolia Search - Remove inactive products from Algolia is not showing at Index Management page.
Also
notification "One or more of the Indexes are not up to date: Algolia Search - Remove inactive products from Algolia. Click here to go to Index Management and rebuild required indexes." at the top is showing forever.
I guess this is the root of the problem I had since Algolia 1.14 - the notification never hides, but I didnt why.
Last time I installed 1.15 on my test site, and found that missing indexer is showing.
Still dont know why its not showing on main site. 
Is this disabled in some config?
OR
Is there any confict with other indexers?
OR
Is this a problem with multi-website Magento?

POSSIBLE RELATED TO:
https://github.com/algolia/algoliasearch-magento/pull/1101
because I have few stores disabled

BUT:
CLI
php shell/indexer.php --reindex algolia_delete_products
works and removes top notification
-->

**Bug: What is the expected behavior?**
To show all indexers

**Bug: What is the proposed solution?**
please check if this works with multi-website. since php files shows some $helper->deleteInactiveProducts($storeId); related things

**Feature: What is your use case for such a feature?**

**Feature: What is your proposed configuration entry? The new option to add? What is the behavior?**

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**

**Comment by JanPetr** [comment] 2019-03-19 15:13
Hello @tomekjordan,

thank you for the report. Could you tell me what version of Magento it's not showing on? I'm not able to reproduce.
At the same time, you are you able to reproduce on the latest `develop` branch of the extension?

**Comment by tomekjordan** [comment] 2019-04-03 23:13
1.9.4.0 with Algolia 1.15
I didn't check the latest develop version, but problem persist since couple last versions,
You weren't able to reproduce this because you dont have multi website enabled, you dont have products in real store (some attributes, different prices per website scope, etc).
The only way to get rid this is to use CLI and php shell/indexer.php --reindex algolia_delete_products
and problem hides until - some product are not changed - meaning new one created, then disabled in admin area. I disable them because I dont use them any more, but I cannot remove the physically because of 3rd party integrations (ERP etc)

**Comment by bsuravech** [comment] 2020-05-15 18:52
Hi @tomekjordan,

My apologies for the delayed follow up. Were you able to resolve your issue with our latest versions of the extension? We are closing the issue here but if the issue you were experiencing is still persistent with our latest version, please feel free to raise the issue by shooting us an email at [support@algolia.com](mailto:support@algolia.com).

**Closed by bsuravech** 2020-05-15 18:52 UTC
