### ISSUE TITLE
Autocomplete not working on Internet Explorer 11

### ISSUE THREAD

**Issue by alicef907** [algolia/algoliasearch-magento#1037] opened 2018-06-15 03:37 UTC
**Bug: What is the current behavior?**
Autocomplete search results not appearing on Internet Explorer 11 after update from 1.13.0 to 1.14.0, not sure if this worked on v 1.13.0. Please contact me for the URL of the website this is occurring on.

**Bug: What is the expected behavior?**
Autocomplete search results should appear when you enter a search string.\

**Bug: What is the proposed solution?**
Unsure, looks like a JS issue, no obvious errors appear at the console though.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Algolia 1.14.0, Magento 1.9.2.4

**Comment by JanPetr** [comment] 2018-06-19 08:11
Hello @alicef907,

thank you for the report! Could you share with me the URL where it happens?
Other browsers work correctly?

When you take a look on Network tab in IE, does Algolia return correct results?

**Comment by alicef907** [comment] 2018-06-19 08:13
Hi Jan,

Thanks for getting back to me on this. The issue is occurring on a site we develop, www.retravison.com.au <http://www.retravison.com.au/>

Everything looks fine on the Network tab in IE.

**Comment by damcou** [comment] 2018-06-21 11:57
Hello @alicef907 

The link you sent us doesn't seem to be available. Maybe the access is restricted as it is in development ?

**Comment by alicef907** [comment] 2018-07-10 00:10
Hi, So sorry I mistyped the URL, it's https://www.retravision.com.au/
Please let me know if you find anything as we're hoping to have this resolved soon!

**Comment by alicef907** [comment] 2018-08-08 01:15
Hi, any updates on this?

**Comment by JanPetr** [comment] 2019-02-14 14:31
Hello @alicef907, we were not able to reproduce on the latest version of the extension.

I'm closing the issue as it's been a while since reported. If you still experience the issue with the latest version, feel free to re-open.

**Closed by JanPetr** 2019-02-14 14:31 UTC
