### ISSUE TITLE
Unable to follow links on iOS

### ISSUE THREAD

**Issue by dustincoates** [algolia/algoliasearch-magento#307] opened 2016-02-03 18:02 UTC
A user reported the following issue:

```I struggled following links on my own iPhone and BrowserStack appears to replicate this behaviour, but Android appears to be fine.```

With a follow-up of:

The iOS issue appeared to be around iOS not picking up on an < a > link around a < div > in the autocomplete popup – this is in the Algolia Autocomplete Template, but we use identical markup on the rest of the site, and it works OK, just not on the Algolia popup for some reason; I didn't get o the root cause, but fixed it by moving the < a > tags around individual elements < p > and < img > tags, and using onClick='javascript:location.url={{url}}' to fire off the link.
 
From looking on StackOverflow and the like, it seemed to be an oddity with iOS at times, and < a > links sometimes do not work – swapping over to onClick is not the best, but seems to fix the issue – note that an < a > link around an < img > tag does not work unless onClick is used, it is odd.

**Comment by maxiloc** [comment] 2016-02-10 09:54
I am not able to reproduce. Let's close this and re-open it if needed

**Closed by maxiloc** 2016-02-10 09:54 UTC
