### ISSUE TITLE
1.6.1 doesn't work

### ISSUE THREAD

**Issue by davids101** [algolia/algoliasearch-magento#543] opened 2016-08-11 07:49 UTC
Upgraded from 1.5.5 to 1.6.1. I get this error message when loading the configuration.

Fatal error: Class 'Algolia_Algoliasearch_Block_System_Config_Form_Field_ProductAdditionalAttributes' not found in /home/server/public_html/app/code/core/Mage/Core/Model/Layout.php on line 590

**Comment by davids101** [comment] 2016-08-11 08:46
Sometimes I wonder if you use your own extension :) I used Magento Connect. Have you guys ever tested it? I had deleted cache before and after.
![algolia-connect](https://cloud.githubusercontent.com/assets/1248017/17583336/1a8c4e52-5f76-11e6-9d7b-d87a073363fd.png)

**Comment by JanPetr** [comment] 2016-08-11 08:48
Yes @davids101,
we do. Did you manage to make it work?

On your screenshot I can see you are using version 1.6.0 so the extension displays you a note about new version. What is wrong?

**Comment by davids101** [comment] 2016-08-11 08:53
That is an old screenshot. What I'm seeing is an error. I don't think the path you gave me corresponds to Magento folder architecture. Didn't I recommend this before? I thought you had fixed this :)

**Comment by davids101** [comment] 2016-08-11 08:55
Discovered the issue! looks like the server created the .php files as folders somehow?

**Comment by davids101** [comment] 2016-08-11 08:57
Here is a screenshot
![algolia-folders](https://cloud.githubusercontent.com/assets/1248017/17583669/b34b35da-5f77-11e6-8ec4-19ac24f29542.png)

**Comment by JanPetr** [comment] 2016-08-11 09:02
> What I'm seeing is an error.

You mean that the note feels more like an error?

> Didn't I recommend this before? I thought you had fixed this :)

It's fixed in 1.7.0-RC, it will go in production soon. Here is a PR: https://github.com/algolia/algoliasearch-magento/pull/517 I tought you will find it :)

> looks like the server created the .php files as folders somehow

Wow, that's weird! Are those folders empty? Do you have any idea how it could happen?

Thanks for your help

**Comment by davids101** [comment] 2016-08-11 09:23
That is great. The folders were empty, I have no idea why that happened

**Comment by JanPetr** [comment] 2016-08-11 09:26
I checked the installation archive, tried to install it couple of times, reinstall and I still cannot reproduce.
Can you try to install it one more time and see if it happens again?

**Comment by davids101** [comment] 2016-08-11 09:29
I was able to reproduce it. I have everything working now, so I'm not going to worry about it. I'm guessing it has something to do with the server.

**Comment by JanPetr** [comment] 2016-08-11 09:31
OK, great. Thanks!

**Closed by JanPetr** 2016-08-11 09:31 UTC
