### ISSUE TITLE
Number of queued jobs never cleared

### ISSUE THREAD

**Issue by maaxxicarvalho** [algolia/algoliasearch-magento#1103] opened 2019-02-14 12:36 UTC
After upgrading to the latest version Algolia Search 1.15.0 the Number of queued jobs never cleared will never empty, it just keeps growing and growing. Apparently, the indexes are being updated but the queue is not being flushed.

**Comment by JanPetr** [comment] 2019-02-14 16:30
Hello @maaxxicarvalho,

I'm not able to reproduce the issue. 
Can you make sure the queue runner can finish the process without error? Is it running every 5 minutes?

**Comment by maaxxicarvalho** [comment] 2019-02-14 16:56
Hi @JanPetr 

The cron is enabled and running every 5 minutes as per instruction. Everything is the same as before, the only thing that changed was the extension version.

**Comment by Karstedt-019** [comment] 2019-02-20 16:06
Any update to this? I have a similar problem.

**Comment by tueaidup** [comment] 2019-03-18 09:30
We're facing the same issue - on one environment it is a clean install of 1.15 - the queue (and estimated finish time) is just increasing every time the cron runs (77k jobs in queue and a finish time of 600 hours).

On another environment (another version of the same shop) we upgraded from a working 1.14 version to 1.15 (to fix prices of out-of-stock subproducts), and the extension still works in that environment.

So we're actually facing the opposite issue of @maaxxicarvalho (upgrade vs clean install).

Both environments is running Magento 1.9.3.1 and PHP7.0, for what it's worth.

**Comment by maaxxicarvalho** [comment] 2019-03-18 13:34
Hi @tueaidup and @Karstedt-019 

Thanks for your inputs, perhaps this will help the issue to be investigated.
It's disappointing to see how the issues related to the Algolia Magento extension are being handled. 

We all know that's an open source extension but, its also promoted as a feature when you go to Algolia's website, as a paid user for a long time I'd expect a way better support.

I had issues in the past and the solution was either to solve by myself or to wait for some miraculous release someday in the unknown future.

In fairness, the service as a whole works pretty well.

**Comment by michaelzangerle** [comment] 2019-03-28 07:46
Hi. We are experiencing the same issue as @maaxxicarvalho. Updated from an older version (1.5) to 1.15 and now it is always showing the following:
> Algolia Search - Indexing queue information: Number of queued jobs: 757, all queued jobs will be processed in appr. 15 minutes, more information about how the indexing queue works you can find in the documentation: Indexing queue

**Comment by greatwitenorth** [comment] 2019-04-04 20:03
Same issue for us. This started right after we updated to to 1.15

**Comment by maaxxicarvalho** [comment] 2019-04-04 20:18
The nice thing is that even with many complaints it seems that nobody gives a shi*&$%#.

The company spends some good money with the Algolia every month, the Magento plugin is offered on the promoted Algolia's Magento page so I don't understand the lack of response, attention, it's like an abandoned project with real customers PAYING a lot of money.

**Comment by damcou** [comment] 2019-04-05 12:26
Hi there,

Thanks for reaching out.
We are sorry for the delay.

As @JanPetr said earlier, this is not an issue we are able to reproduce on our own servers during our tests and the fact that most of our customers are not experiencing similar issues tends us to think that your problem is specific to your configuration or environment.

We do understand that the indexing queue is probably the most complex part of the extension, and yes unfortunately , some customers can experience some trouble during usage depending on their setup.
That’s why we’re currently working on this feature to enhance it. We also released a troubleshooting guide to help them to find what can be the blocking point : https://www.algolia.com/doc/integration/magento-2/troubleshooting/technical-troubleshooting/ (this guide has been made for Magento2 but it’s also valid for Magento1).   

We also make our best to provide support by email (support@algolia.com) when it comes to help our paying customers on an individual basis to facilitate the implementation of Algolia and troubleshoot issues if they have. 

The Github issues are made to point very precise technical parts of the code of the extension to :
- Propose an enhancement/fix 
- Discuss about a particular error displayed at some point during the process
- Discuss/ask about new features

For this particular topic, I’d recommend to go through the technical troubleshooting guide and see if you can identify your issue this way. During your investigations, if you can find errors in your logs generated by the extension or a particular portion of the code that makes you think it needs to be fixed, feel free to post them here. 

I hope the troubleshooting guide will help. If not, please reach out the customer support. 
Best regards.

**Comment by maaxxicarvalho** [comment] 2019-04-05 13:04
Hello @damcou 

Thanks for your feedback.

As for your suggestion for paying customers to use the **support@algolia.com** channel, well, I did it more than once before and whoever replies the email points to either Github or Algolia's Discourse Community.   
That's pretty clever actually, you have your customers to pay for your service, then the same customers will pay for developers to find issues on your codebase and give support for free to other paid customers, and all of that using free tools like Github and Discourse, amazing strategy, I'm really impressed!

Now, about the issue that we and others are having regarding the queue.  
As you can see from the comments above, **it wasn't happening before the plugin upgrade**, which means that's something that was introduced by **your** changes and not ours.

You also said **the indexing queue is probably the most complex part of the extension**. So let's get this straight.  
**You changed** your extension's features and logic at some point.  
Then we upgraded following the best practices and notifications that **your** extension shows on the Admin Panel saying that there's a new version available.  
And now **we** must debug your code, find the problem that you introduced and point you in the correct direction to solve it!

I honestly wish that I had this idea that you guys had before in my life, amazing!

----

I also have to say that this problem we are having has nothing to do with the Algolia search service as a whole, which works great and I don't have any complaints about it.

The problem is the support, it offers one of the worst services I ever faced during my life as a developer.

**Pre-sales team is amazing by the way.

**Comment by greatwitenorth** [comment] 2019-04-05 17:31
@damcou thanks for your response. But I might add that you have 5 different people in this thread reporting the same issue after upgrading. So I think it might have a little more to do with code changes rather than a particular setup. Also this is only the 5 who have reported (there's likely many more).

With that out of the way lets see how we can fix this issue 😄. My guess is that the trouble lies somewhere here:
https://github.com/algolia/algoliasearch-magento/blob/9357b9e44f5067d986fdb319cb152037a52edc95/app/code/community/Algolia/Algoliasearch/Model/Queue.php#L150-L151

Although I haven't had a chance yet to step through the code when the cron is run.

**Comment by JanPetr** [comment] 2019-04-08 07:37
Hello everybody,

thank you for all the reports. We are trying to reproduce the issue, but we're not able to - even out tests are passing correctly.

Would you be able for you to export contents of `algoliasearch_` DB tables from your Magentos and send it to us? It will help us understand what is happening in your queues and why the jobs are not cleared from there as they should.

Thank you!

**Comment by JanPetr** [comment] 2019-04-08 07:40
@greatwitenorth 
 
> With that out of the way lets see how we can fix this issue 😄. My guess is that the trouble lies somewhere here:
> [algoliasearch-magento/app/code/community/Algolia/Algoliasearch/Model/Queue.php](https://github.com/algolia/algoliasearch-magento/blob/9357b9e44f5067d986fdb319cb152037a52edc95/app/code/community/Algolia/Algoliasearch/Model/Queue.php#L150-L151)
> 
> Lines 150 to 151 in [9357b9e](/algolia/algoliasearch-magento/commit/9357b9e44f5067d986fdb319cb152037a52edc95)
> 
>                  $where = $this->db->quoteInto('job_id IN (?)', $job['merged_ids']); 
>                  $this->db->delete($this->table, $where); 
> Although I haven't had a chance yet to step through the code when the cron is run.

I just gave it a try and the `$job['merged_ids']` are always populated and jobs correctly deleted. There is not even a transaction going on which would eventually rolled back the delete query :/ There seems to be some glitch not visible to us,

**Comment by greatwitenorth** [comment] 2019-04-08 21:02
Thanks @JanPetr. Just sent an email to support@algolia.com with a dump of my algoliasearch_ tables.

**Comment by JanPetr** [comment] 2019-04-09 07:49
Thank you, @greatwitenorth!

We added some changes / fixes to `develop` branch just now (#1118, #1117). Could you give it a try and see if it resolves / helps your issues?

Thank you!

**Comment by rbrown** [comment] 2019-04-12 10:27
Hey, I've inadvertently started using this code, I'm not sure it's working as intend but there are no dead jobs left in my queue. I read though the changes and is locked_at supposed to be doing/for anything? Before 843e308 locked_at was being set to the current time by getJobs, but the new lockJobs function just seems to update the pid, not locked_at? And locked_at isn't being using for job selection either?

**Comment by bsuravech** [comment] 2019-04-12 11:24
Hey @rbrown! Thank you for the update on that! We have created a new PR with the inclusion of the version and update of the lockJobs() method. You can review this PR here: #1124

**Comment by tueaidup** [comment] 2019-04-29 09:59
We upgraded from 1.15 to 1.16, and manually emptied the queue (272k jobs!) before reindexing again. It seems that the problem has been resolved.

**Comment by bsuravech** [comment] 2019-11-08 16:40
Hi everyone! As mentioned previously, this issue has been addressed in PR#1124 and has since been incorporated into the latest version. If you have upgraded to the latest version and are still experiencing issues with stuck jobs, please feel free to open a new issue here. Thanks!

**Closed by bsuravech** 2019-11-08 16:40 UTC
