### ISSUE TITLE
Facet collapse and show more/less

### ISSUE THREAD

**Issue by royduin** [algolia/algoliasearch-magento#716] opened 2017-01-04 15:52 UTC
instantsearch.js does have multiple options for the `refinementList`, `hierarchicalMenu`, etc. For example the `collapsible` and `showMore` options. I've implemented those earlier as mentioned here: https://github.com/algolia/algoliasearch-magento/issues/537. It's working great after applying some extra styling afterwards but it would be nice if this is a default configuration functionality in the Algolia Magento module.

I can't find a roadmap so hereby a feature request :)

**Comment by JanPetr** [comment] 2017-01-05 22:15
Thanks for the suggestion @royduin, good idea. The issue is that as you said, there are many options and it's not easy to keep all the options configurable and implemented in the extension out of the box as it'd bring more complexity to the UI of the extension.
And not all those options aren't required for most of the customers.

This is something we would like to solve by introducing custom hooks in JS code (https://github.com/algolia/algoliasearch-magento/pull/642), so you'll be able to hook your code and add needed parameters to specific widgets without tweaking the extension. Would that work for you? If you find some time, I'd really appreciate your feedback on the pull request and if there are some hooks missing, I'll be happy to add them.

Thanks!

**Comment by royduin** [comment] 2017-01-06 11:08
Custom hooks would be awesome, that way people can modify it easily without the need of overwriting the complete file. I would say: merge your pull request and this issue can be closed.

**Comment by JanPetr** [comment] 2017-01-10 23:04
Will be handled by hooks from #631, closing now.
If you have something to add @royduin, feel free to reopen.

**Closed by JanPetr** 2017-01-10 23:04 UTC
