### ISSUE TITLE
Store View Specific facets do not work

### ISSUE THREAD

**Issue by dmytro-butko** [algolia/algoliasearch-magento#857] opened 2017-06-26 03:39 UTC
We have facets (and attributes) defined on default (global) level.
All works great for all the store views.

However we've tried to override facets for some specific store view and all the facets gone from the results page. Switching back to 'default config' works ok.

Is there any specific logic around it? Of course, all the facets we've tried to use on a store view level are indexed/etc.

**Comment by JanPetr** [comment] 2017-07-04 10:46
Hello @dmytro-butko,

thanks for the report. I just checked and I cannot reproduce the issue. Everything works as expected.

**My configuration:**

Default config:
<img width="1158" alt="screenshot 2017-07-04 12 41 43" src="https://user-images.githubusercontent.com/1058144/27827221-83683322-60b6-11e7-9a73-a1f2c876c688.png">


English store config:
<img width="1248" alt="screenshot 2017-07-04 12 43 05" src="https://user-images.githubusercontent.com/1058144/27827220-83667e24-60b6-11e7-91d4-3efb0067e781.png">

French store config:
<img width="1242" alt="screenshot 2017-07-04 12 42 11" src="https://user-images.githubusercontent.com/1058144/27827218-83660322-60b6-11e7-8743-40cac07db4f5.png">

English search page: 
<img width="1217" alt="screenshot 2017-07-04 12 43 21" src="https://user-images.githubusercontent.com/1058144/27827219-8365ff44-60b6-11e7-835d-e10aae36d190.png">

French search page:
<img width="1218" alt="screenshot 2017-07-04 12 43 32" src="https://user-images.githubusercontent.com/1058144/27827217-83653672-60b6-11e7-8d19-518811540e53.png">

Did you try to reindex your data when you change the store-specific facets?

**Comment by dmytro-butko** [comment] 2017-07-05 00:12
thanks and okay.

after playing more with it, the issue actually to be re-phrased as:
 if store view facet is not a subset of default view facets -> it won't
show up on store view level

so in your config to reproduce:
 1. remove color as facet from default config
 2. visit french store view

regards.

**Comment by JanPetr** [comment] 2017-07-05 08:31
Thanks @dmytro-butko,

I'm able to reproduce now. Will investigate and come back to you. Thanks for the additional info.

**Comment by JanPetr** [comment] 2017-07-12 12:55
Will be part of the next release.

**Closed by JanPetr** 2017-07-12 12:55 UTC
