### ISSUE TITLE
Catalog Price Rules

### ISSUE THREAD

**Issue by Ilia** [algolia/algoliasearch-magento#324] opened 2016-02-24 04:38 UTC
Hi,

Can you please confirm if the prices transferred to algolia are affected by the catalog price rules? 

In my testing I found that if i set the special price and have a catalog price rule on top with no group price on the product itself, it will only transfer the special price to algolia. Customer Groups in config is set to "Yes".

Any feedback on this would be greatly appreciated.

**Comment by maxiloc** [comment] 2016-02-24 10:00
@Ilia Which version of the extension are you using ? I am not able to reproduce it locally

**Comment by Ilia** [comment] 2016-02-24 10:09
@maxiloc using the latest release 1.5.3, we have catalog price rules that affect the special prices as well as full price, we do not use the group prices on the products themselves. Looking at the product helper class around the handleprice method, there does seem to be a mention of catalog price rules model.. I must be missing something.

**Comment by maxiloc** [comment] 2016-02-24 10:23
Yes this call https://github.com/algolia/algoliasearch-magento/blob/master/code/Helper/Entity/Producthelper.php#L318
is handling both special price and any catalog price rule that there can be.

Same here https://github.com/algolia/algoliasearch-magento/blob/master/code/Helper/Entity/Producthelper.php#L328 when customer group is enabled.

**Comment by Ilia** [comment] 2016-02-24 10:26
Thank you, will debug that and see why it is not working for me

**Comment by maxiloc** [comment] 2016-03-15 21:49
I am closing this, let's re-open if needed

**Closed by maxiloc** 2016-03-15 21:49 UTC
