### ISSUE TITLE
Placeholder image get indexed instead of actual image

### ISSUE THREAD

**Issue by manish172** [algolia/algoliasearch-magento#691] opened 2016-12-02 22:58 UTC
when assign the image at store scope level (Multi-store Product setup), Placeholder image get indexed as there is no image assigned at default level

**Comment by JanPetr** [comment] 2017-01-06 00:00
Hello @manish172,
sorry for the very late answer.
I tried to reproduce the issue but I didn't manage.

Do you mind investigating in the code of the extension why the correct image is not loaded?
The images' URLs are assigned to product here: https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php#L768-L812
And here is the code of our Image helper: https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/Helper/Image.php

I'll be happy if you'd help me with investigating.

Thank you very much!

**Comment by dudusotero** [comment] 2017-01-09 11:47
I have the same problem. Any idea what it might be?

**Comment by JanPetr** [comment] 2017-05-04 08:55
Hello @manish172,

since I didn't hear from you for a while and I'm still not able to reproduce the issue, I'm closing this one.
If you still experience the issue, feel free to reopen.

**Closed by JanPetr** 2017-05-04 08:55 UTC
Labels: investigate
