### ISSUE TITLE
Categories not being removed after deleting

### ISSUE THREAD

**Issue by jlaustill** [algolia/algoliasearch-magento#780] opened 2017-03-01 17:38 UTC
We seem to be having an issue whereby categories aren't being removed from the index when we remove them.  If you go to www.north40.com and search for real ranching sale you will see a category on the left with 330 products.  When you click it, it takes you to the instant search page and displays zero products, which is correct because we deleted this category.  It doesn't even exist in the backend.  

I assume I can manually delete the index in algolia and reindex and it will fix it, but is there an option for this I am missing?  Other than this all of our other indexes seem to be updating properly.

**Comment by JanPetr** [comment] 2017-03-01 17:42
Hello @jlaustill,

thanks for the report, I can reproduce on your website.
Can I ask you how did you remove the category? You went to a category administration and just deleted it?
I'm asking because I need to understand your workflow as there are maybe some use-cases which we missed in the extension.

Thank you for your help.

**Comment by jlaustill** [comment] 2017-03-01 20:49
My ecom manager sent me this response "So maybe you can re-word your question...we don't delete the categories, we change them...like change the products or the name of the category"

So essentially it seems like when we rename a category or change the products assigned they aren't updating.  We use these for temporary sales, that may or may not be the Magento standard?

**Comment by michaelscheel** [comment] 2017-03-24 17:01
The extension currently only re-indexes the category index and does not update the related products when renaming a category. We had the same issue and solved it. I could create a PR if that is an intended functionality.

**Comment by JanPetr** [comment] 2017-05-04 09:43
Hello @jlaustill,
I finally have found time to investigate your issue.

When I rename any category, the change is automatically propagated to Algolia's category index. So when you search in autocomplete menu there should always be the correct name:

<img width="722" alt="screenshot 2017-05-04 11 37 01" src="https://cloud.githubusercontent.com/assets/1058144/25698180/1b4a480c-30be-11e7-8ac6-2b72c825951d.png">
<img width="927" alt="screenshot 2017-05-04 11 37 33" src="https://cloud.githubusercontent.com/assets/1058144/25698182/1dff5a56-30be-11e7-8f06-cd731b1be0db.png">

If you can see still the old name there, it can be caused by indexing queue (if you have enabled it) which might cause a delay between change and reindexing (queue runner doesn't have to process the reindexing immediately).

When you change the name, by default only category change is propagated to Algolia. But the old name is assigned to all products from the category. Which results in wrong name in facet filter and may result in empty category.
To fix that you need to reindex your product catalog or to enable `Update all category products on category update` option in Algolia configuration:
<img width="629" alt="screenshot 2017-05-04 11 41 52" src="https://cloud.githubusercontent.com/assets/1058144/25698311/ae723b80-30be-11e7-94c7-89eb2a3ea138.png">
This option is by default turned off as it might cause a big delays on category save. But when you enable it, when you change category name all it's products will be automatically reindexed with the new name as well and there won't be any issues (but again, there might be a delay because of indexing queue).

Let me know if it helps you or if you still experience the issue.

**Closed by JanPetr** 2017-05-04 09:43 UTC
Labels: investigate
