### ISSUE TITLE
Autocomplete + Mobile: first touch hovers the product, second touch clicks

### ISSUE THREAD

**Issue by julienbourdeau** [algolia/algoliasearch-magento#932] opened 2017-10-09 12:12 UTC
Today, on mobile and with Algolia autocomplete, you need to touch twice to go to from the result list to the product page.

It could makes sense to avoid clicks while you're just scrolling but it could also be confusing to have to click twice.

Do we want to keep this behaviour.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1525636/31337497-e6d5b52e-acfb-11e7-8f55-cf8d3dd4db17.gif)

**Comment by JanPetr** [comment] 2017-10-30 13:54
Thanks for the issue Julien. I'm closing it as it's duplicate of #902 :)

**Closed by JanPetr** 2017-10-30 13:54 UTC

**Comment by julienbourdeau** [comment] 2017-10-30 16:45
Sorry I didn't go through the opened issues ^^

I was quite happy to test the new record screen feature on iOS 11 tho. ;)
