### ISSUE TITLE
Segmentation fault when reindexing products

### ISSUE THREAD

**Issue by davecoggins** [algolia/algoliasearch-magento#508] opened 2016-07-18 15:32 UTC
I've got the extension installed and the indexes set to use the CRON. All indexes process fine except for the product index. I have set `Max number of element per indexing job` and `Number of jobs to run each time the cron is run` to 1. I have also disable Agolia on all but one store for testing purposes. 

When I run the product indexer 574 row are added to `algoliasearch_queue` table. When this is processed by `algolia_queue_runner` I get a segementation fault when processing the first row. The row gets a `pid` but there are no error logs in `var` directory. 

I have turned on xdebug and this is some of the output:

`0.0465    1043640   1. {main}() /home/vagrant/acme/vendor/aoepeople/magento-deployscripts/n98-magerun.phar:0
    0.0752    2492336   2. N98\Magento\Application->run() /home/vagrant/acme/vendor/aoepeople/magento-deployscripts/n98-magerun.phar:8
    0.3366   13139024   3. Symfony\Component\Console\Application->run() phar:///home/vagrant/acme/vendor/aoepeople/magento-deployscripts/n98-magerun.phar/src/N98/Magento/Application.php:643
    0.3367   13139248   4. N98\Magento\Application->doRun() phar:///home/vagrant/acme/vendor/aoepeople/magento-deployscripts/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:126
    0.3387   13173208   5. Symfony\Component\Console\Application->doRun() phar:///home/vagrant/acme/vendor/aoepeople/magento-deployscripts/n98-magerun.phar/src/N98/Magento/Application.php:583
    0.3388   13174128   6. Symfony\Component\Console\Application->doRunCommand() phar:///home/vagrant/acme/vendor/aoepeople/magento-deployscripts/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:195
    0.3403   13188728   7. N98\Magento\Command\AbstractMagentoCommand->run() phar:///home/vagrant/acme/vendor/aoepeople/magento-deployscripts/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:882
    0.3403   13189128   8. Symfony\Component\Console\Command\Command->run() phar:///home/vagrant/acme/vendor/aoepeople/magento-deployscripts/n98-magerun.phar/src/N98/Magento/Command/AbstractMagentoCommand.php:430
    0.3405   13193840   9. N98\Magento\Command\Indexer\ReindexCommand->execute() phar:///home/vagrant/acme/vendor/aoepeople/magento-deployscripts/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
    0.8091   21940304  10. Mage_Index_Model_Process->reindexEverything() phar:///home/vagrant/acme/vendor/aoepeople/magento-deployscripts/n98-magerun.phar/src/N98/Magento/Command/Indexer/ReindexCommand.php:104
    0.8143   21999208  11. Mage_Index_Model_Process->reindexAll() /home/vagrant/acme/htdocs/app/code/core/Mage/Index/Model/Process.php:260
    0.8790   22691424  12. Algolia_Algoliasearch_Model_Indexer_Algoliaqueuerunner->reindexAll() /home/vagrant/acme/htdocs/app/code/core/Mage/Index/Model/Process.php:212
    0.8792   22692392  13. Algolia_Algoliasearch_Model_Queue->runCron() /home/vagrant/acme/.modman/algoliasearch-magento/code/Model/Indexer/Algoliaqueuerunner.php:74
    0.8793   22693656  14. Algolia_Algoliasearch_Model_Queue->run() /home/vagrant/acme/.modman/algoliasearch-magento/code/Model/Queue.php:57
    0.9666   24078464  15. Algolia_Algoliasearch_Model_Observer->rebuildProductIndex() /home/vagrant/acme/.modman/algoliasearch-magento/code/Model/Queue.php:200
    1.4455   30333320  16. Algolia_Algoliasearch_Helper_Data->rebuildStoreProductIndexPage() /home/vagrant/acme/.modman/algoliasearch-magento/code/Model/Observer.php:208
    2.5415   41591928  17. Varien_Data_Collection->walk() /home/vagrant/acme/.modman/algoliasearch-magento/code/Helper/Data.php:562
    2.5415   41592736  18. call_user_func_array:{/home/vagrant/acme/htdocs/lib/Varien/Data/Collection.php:466}() /home/vagrant/acme/htdocs/lib/Varien/Data/Collection.php:466
    2.5416   41593000  19. Mage_Core_Model_Abstract->clearInstance() /home/vagrant/acme/htdocs/lib/Varien/Data/Collection.php:466
    2.5419   41595304  20. Mage_Catalog_Model_Product->_clearData() /home/vagrant/acme/htdocs/app/code/core/Mage/Core/Model/Abstract.php:569
    2.5419   41595352  21. Mage_Catalog_Model_Product->reset() /home/vagrant/acme/htdocs/app/code/core/Mage/Catalog/Model/Product.php:2020
    2.5420   41595520  22. Mage_Catalog_Model_Product->_clearData() /home/vagrant/acme/htdocs/app/code/core/Mage/Catalog/Model/Product.php:1883
    2.5420   41600840  23. Mage_Catalog_Model_Product->reset() /home/vagrant/acme/htdocs/app/code/core/Mage/Catalog/Model/Product.php:2020
    2.5420   41600840  24. Mage_Catalog_Model_Product->_clearData() /home/vagrant/acme/htdocs/app/code/core/Mage/Catalog/Model/Product.php:1883
    2.5420   41606160  25. Mage_Catalog_Model_Product->reset() /home/vagrant/acme/htdocs/app/code/core/Mage/Catalog/Model/Product.php:2020
    2.5420   41606160  26. Mage_Catalog_Model_Product->_clearData() /home/vagrant/acme/htdocs/app/code/core/Mage/Catalog/Model/Product.php:1883
    2.5421   41611480  27. Mage_Catalog_Model_Product->reset() /home/vagrant/acme/htdocs/app/code/core/Mage/Catalog/Model/Product.php:2020
    2.5421   41611480  28. Mage_Catalog_Model_Product->_clearData() /home/vagrant/acme/htdocs/app/code/core/Mage/Catalog/Model/Product.php:1883
    2.5421   41616800  29. Mage_Catalog_Model_Product->reset() /home/vagrant/acme/htdocs/app/code/core/Mage/Catalog/Model/Product.php:2020
    2.5421   41616800  30. Mage_Catalog_Model_Product->_clearData() /home/vagrant/acme/htdocs/app/code/core/Mage/Catalog/Model/Product.php:1883
    2.5422   41622120  31. Mage_Catalog_Model_Product->reset() /home/vagrant/acme/htdocs/app/code/core/Mage/Catalog/Model/Product.php:2020
    2.5422   41622120  32. Mage_Catalog_Model_Product->_clearData() /home/vagrant/acme/htdocs/app/code/core/Mage/Catalog/Model/Product.php:1883`

This continues to 512 entries until I presume it runs out of memory.

Any thoughts as to what I am doing wrong?

**Comment by JanPetr** [comment] 2016-07-20 09:39
Hello @davecoggins,
I took a look on the log you posted bu I cannot find any error there. It's just a stack-trace.

Can you investigate in [here](https://github.com/algolia/algoliasearch-magento/blob/master/code/Model/Queue.php#L144-L215) to see which jobs and products are processed and what is going on in general?

**Comment by davecoggins** [comment] 2016-07-25 10:19
Hi @JanPetr 

I have had a poke around and think I have narrowed the segmentation fault down to line line 562 of `code/Helper/Data.php` which is:

`$collection->walk('clearInstance');`

After running `php -i | grep memory_limit` I get max memory limit:

`memory_limit => 2048M => 2048M`

Not sure how to go from here....

**Comment by JanPetr** [comment] 2016-07-26 09:54
Thanks @davecoggins,
it looks weird. It seems like your whole catalogue is being processed and not only required subset. That is most probably the reason why your memory is running out. 
Can you investigate in the part of the code I sent you in previous comment and see how many jobs are proccessing? I'm not able to reproduct on my side ...

**Comment by JanPetr** [comment] 2016-08-01 09:59
Any update on this one @davecoggins?

**Comment by davecoggins** [comment] 2016-08-01 10:05
@JanPetr I've had to shelve this for time being to sort something else out but from memory only 1 job was being processed when I checked through the code.

**Comment by JanPetr** [comment] 2016-10-18 09:25
Hello @davecoggins,
I didn't hear from you for a while. Did you manage to sort it out?
I'm closing the issue right now, but feel free to re-open.

**Closed by JanPetr** 2016-10-18 09:25 UTC
Labels: Question

**Comment by Adel-Magebinary** [comment] 2018-05-02 00:46
We had the same issue.
