### ISSUE TITLE
Reindexing issue : Storeview pages get affected

### ISSUE THREAD

**Issue by Nisha-Jangid** [algolia/algoliasearch-magento#1056] opened 2018-09-17 05:21 UTC
**Do you want to request a *feature* or report a *bug*?**
Feature

**Feature: What is your use case for such a feature?**
Like we are using Algolia 1.13.0 search extension in magento 1, On re-indexing our website pages get blank. Only header and footer get display in this case. Also re-indexing takes too much time. 

**Feature: What is solution for this issue?**
Is there any solution for this issue which takes less time on re-indexing and re-indexing does not effect frontend view.

**What is the version of Magento and of Algolia extension you are using?**
Magento version - 1.9.3.8
Algolia version - 1.13.0

**Comment by JanPetr** [comment] 2019-02-14 10:43
Hello @Nisha-Jangid,

thank you for the report.
We are not able to reproduce the issue. Could you take a look into your logs and see if anything goes wrong during the reindex? Are there any errors or warnings during the reindexing?

I'm closing the issue now as it's been a while since it was reported. Feel free to re-open if you still experience the issues. Thank you!

**Closed by JanPetr** 2019-02-14 10:43 UTC
