### ISSUE TITLE
When the product stock reaches 0, the catalog image are replaced by empty placeholder

### ISSUE THREAD

**Issue by dudusotero** [algolia/algoliasearch-magento#738] opened 2017-01-24 12:58 UTC
I created this issue because I could not reopen the task #686 @JanPetr .

I discovered how to reproduce the problem, when a product reaches 0 in stock its image in the catalog is replaced by an empty placeholder. To fix this it is necessary to reindex the Algolia catalog again, but this is not the best way. Is there any way around this?

Thanks for the support!

-Edit-
I use configurable product, so if the size G of a product runs out, there are still other sizes in stock, so I can not simply remove them from the catalog.

**Comment by JanPetr** [comment] 2017-08-03 15:39
I couldn't reproduce the issue and don't have any other reports about it. So I'm closing the issue.
If you still experience the issue even in newer versions, feel free to reopen.

**Closed by JanPetr** 2017-08-03 15:39 UTC
Labels: investigate
