### ISSUE TITLE
Disabled/Enabled extension - still showing One or more of the Indexes are not up to date: Algolia Search - Delete inactive products

### ISSUE THREAD

**Issue by tomekjordan** [algolia/algoliasearch-magento#1058] opened 2018-10-03 23:56 UTC
HI. Latest Algolia.

1. I disabled Algolia extension for a while (testing extensions incompatibility). Just by changing etc name
2. I re-enabled.
3. indexing is working. all indexers are fresh SCREENSHOT [http://prntscr.com/l1wn3c](url)
I even emptied queue with EMPTY_QUEUE=1 php -f /absolute/path/to/magento/shell/indexer.php -- -reindex algolia_queue_runner
4. messegae "One or more of the Indexes are not up to date: Algolia Search - Delete inactive products. Click here to go to Index Management and rebuild required indexes." still appear in the admin area.
How to get rid of it?

**Comment by JanPetr** [comment] 2019-02-14 10:44
Duplicate of #1052

**Closed by JanPetr** 2019-02-14 10:44 UTC
