### ISSUE TITLE
Same name categories with different paths showing all products combined

### ISSUE THREAD

**Issue by glozano** [algolia/algoliasearch-magento#987] opened 2017-12-14 22:00 UTC
Hi, we have a Magento 1.9.3.7 and are using Algolia 1.12.0.

The issue we're experimenting is that our products get mixed together whenever the category name is the same, no matter what the category path is. 

Here's a look into the Magento categories:
![captura de pantalla 2017-12-14 a la s 18 40 49 copy](https://user-images.githubusercontent.com/1132977/34016364-591c6a78-e100-11e7-8490-88b2313028eb.png)

But then in Algolia I see this:
![captura de pantalla 2017-12-14 a la s 18 41 25](https://user-images.githubusercontent.com/1132977/34016373-62cf4b26-e100-11e7-9871-37b8ed8a6367.png)

And as a result, instead of the 1 product that should be shown in the frontend, we get the 9 combined:

![captura de pantalla 2017-12-14 a la s 18 51 35 copy](https://user-images.githubusercontent.com/1132977/34016394-781429ac-e100-11e7-9f74-6e51af0315e0.png)

Hope you can shed some light to this issue, let me know if I can be of any assistance

Thanks!

**Comment by glozano** [comment] 2017-12-20 13:36
Any update on this?
Thanks

**Comment by JanPetr** [comment] 2017-12-21 09:46
Hello @glozano,

I'm not able to reproduce.
Would you mind sharing with me a website where I could see the issue live?

Thanks!

**Comment by damcou** [comment] 2018-08-27 13:39
Hi @glozano , I don't know if you have still the issue. I'll close this ticket but feel free to reopen it if you're still experiencing it.

**Closed by damcou** 2018-08-27 13:39 UTC
