### ISSUE TITLE
Unindex a product in Algolia when its configurable is inactive

### ISSUE THREAD

**Issue by schwipps** [algolia/algoliasearch-magento#425] opened 2016-06-02 09:11 UTC
[At the end of this issue](https://github.com/algolia/algoliasearch-magento/issues/401), I explained that some products wouldn't get unindexed by Algolia if any childs of an inactive configurable remains active.
To prevent this behavior, we've built an SQL request which unactivates all subproducts for which the parent is. We can launch this request twice a day.
This request seems to do what it's supposed to as I can see after the request's passed, these simple products as disabled in backoffice.

The point is that a full reindex (Algolia included) won't do anything : indeed, the product remains indexed in Algolia.
To really achieve what I want, I have to update the configurable as inactive (even though if it's already inactive), and then reindex Algolia.

All of this is kind of painful. Could you insert a controlclose to Producthelper.php:813 (Set main product out of stock if  sub-products is out of stock) to remove from index all subproducts whose parent is inactive ? Because if the configurable is inactive (and of course its simples aren't visible individually), there's no reason for it to be indexed in Algolia anymore.

**Comment by maxiloc** [comment] 2016-06-02 10:12
@schwipps Makes sense, we just need to check the magento behavior on this one and make sur ewe are doing the same. We'll keep you up to date

**Comment by schwipps** [comment] 2016-06-02 10:34
Nice, thanks.
Let me know when it's available. After what we should be available to activate Aloglia in production pretty quickly.

**Comment by JanPetr** [comment] 2016-06-02 14:16
@schwipps I'm reopening the issue so we can keep eyes on it and do not forget about the feature :)

**Comment by JanPetr** [comment] 2016-06-08 12:40
Hello @schwipps,
I tried to investigate your issue and played a bit with configurable products.

I realized that in the extension we do the same thing as Magento does.

When configurable product is disabled and has some enabled children products - we do not include the configurable product in Algolia index. It is removed because the product itself is disabled.

When configurable product is enabled, but all his children products are disabled, we do not include this configurable product in Algolia index as well.

When configurable product is disabled, but some of his children are enabled and are set to be visible in search, they are indexed in Algolia.

Magento itself does the same way.

Did I miss your use case? I cannot reproduce your issue 😕

**Comment by JanPetr** [comment] 2016-06-08 12:55
> The point is that a full reindex (Algolia included) won't do anything : indeed, the product remains indexed in Algolia.

When you are disabling the product, do you trigger standart Magento hooks? Because the extension depends on it and when you do the change directly in DB, no reindex is triggered.

> To really achieve what I want, I have to update the configurable as inactive (even though if it's already inactive), and then reindex Algolia.

Are you sure that the reindex removes the product from Algolia? Cannot it be only updating the product? Because in current version is a bug with removing products from Algolia when reindexing. It's fixed with this commit: https://github.com/algolia/algoliasearch-magento/commit/11fa9ef6bc9baa56ef9ba75214a615e4099b83aa

**Comment by schwipps** [comment] 2016-06-14 14:00
Hi @JanPetr,

Sorry for the delay.

You right, our request didn't trigger standart Magento hooks.
I also had updated only a few files from the dev branch, but not the whole repository.
Thus, as you said this branch had some improvements related to our subject, I just did a wider update, then processed to a full reindex.

Unfortunately, I still get inactive products in the search suggestions.

On one of them, I did the same manipulation : I disabled the configurable and its children (the configurable is not enough) from the backoffice (change status), then process the Algolia index queue. That's the only way I get rid of the product.

**Comment by JanPetr** [comment] 2016-06-14 15:25
Hey @schwipps,
if I understand it right you updated your extension with development branch and reindexed your products.
But it did not remove your products, correct?

Did you have the `Remove disabled products as part of indexing` option turned on? It's turned off by default.

**Comment by schwipps** [comment] 2016-06-14 15:47
I just did, but still no more results, after Algolia, and full reindex.

**Comment by JanPetr** [comment] 2016-06-14 16:15
Can you check if the IDs of products which are supposed to be removed on reindex are in `$nonIndexableProductIds` variable here: https://github.com/algolia/algoliasearch-magento/blob/develop/code/Helper/Data.php#L570 ?

**Comment by JanPetr** [comment] 2016-06-21 09:40
Hello @schwipps,
my latest answer to you is already out-dated. We completly refactored whole products' re-indexing part of our extension. Now when you have `indexing queue` enabled, the re-indexing uses temporary indices and indexes only correct products. It's part of our Release Candidate pre-release which we released yesterday.
Can you download it and test products re-indexing with enabled indexing queue? I believe it should fox your issue.

**Comment by schwipps** [comment] 2016-06-21 13:40
Hi,

I updated the module, and after clearing all caches, reloading php and webserver, I keep getting, on reindex :
`PHP Fatal error:  Call to undefined method Algolia_Algoliasearch_Model_Observer::removeProducts() in /var/www/.../app/code/community/Algolia/Algoliasearch/Model/Queue.php on line 200`

I inspected the RC repository, and my files, and can't find any occurence of 'removeProducts'. so I don't understand why I get this warning.
Something on your side ?

**Comment by JanPetr** [comment] 2016-06-21 13:53
You will have to clean your `algoliasearch_queue` table as well. There are records which tries to call this undefined method.

**Comment by schwipps** [comment] 2016-06-21 15:38
Thanks, this point is now solved.
Now I have about 2300 products in Algolia's index, and 3300 Enabled / Visible and Searchable in backoffice.
Algolia indexes are still shown as processing on bakoffice when completed.

Finally I used to display in the autocomplete section the brand of the product (I edited autocomplete.phtml by adding {{{_highlightResult.marque.value}}}, but it doesn't seem to work anymore. In the index, I now see a number value instead of the brand.
Is there an new way to request custom attributes ?

Thanks!

**Comment by JanPetr** [comment] 2016-06-21 16:28
And is the reindex finished or is it still processing? Are there any products which should be indexed but they are not?

Do you send `marque` attribute to Algolia? Is it set as indexable and searchable attribute here? https://www.dropbox.com/s/vlzu52nmjnk6cq8/Screenshot%202016-06-21%2018.28.41.png?dl=0

**Comment by schwipps** [comment] 2016-06-21 17:19
Yes to both

**Comment by JanPetr** [comment] 2016-06-22 08:12
And can you find any concrete products which should be indexed and is not? That would be great so we can investigate why it's not indexed.

About the `marque` attribute - it's a numeric attribute. And numerical attributes are not highlighted in Algolia engine. It must be send as text (string) to Algolia. Then it will be highlighted and accessible from `_highlightResult`. Bu default, the extension casts all attributes to correct data types, but you can force `marque` attribute to be casted to string here: https://github.com/algolia/algoliasearch-magento/blob/develop/code/Helper/Entity/Helper.php#L55-L79

**Comment by schwipps** [comment] 2016-06-22 12:27
It will be easier to detect missing products if I have the brand, so I'd like to handle the attribute first.

On this point, I'm not sure to get what I have to do with the code you point.

The attribute `marque` used to be displayed as plain text the way it was built, and nothing changed on our site about it. Shall I declare it differently now ?

What am I supposed to do with this function ?
I tried to add `marque` after sku, name and description. Nothing happened.
So I pedaled back... Now I just lost all my products on Algolia's index.........

**Comment by JanPetr** [comment] 2016-06-22 12:57
When I checked the data in attribute `marque` there was a number, not a brand name. Are you sure that in this attribute in Magento you have a name of the brand?
You can take a look into Algolia dashboard into your indices to check what data are indexed in Algolia.

If you have no data, can you just reindex them again?

**Comment by schwipps** [comment] 2016-06-22 13:45
All I can say is that I used to find a product in your tool by typing it.
From yesterday, it didn't work anymore because, as you say, the id of the product brand was transmitted instead of the value. And today, I don't have data anymore.

I just did an Algolia reindex -> no more products. Full reindex -> same thing.

**Comment by JanPetr** [comment] 2016-06-23 07:52
Sorted out via support e-mail.

**Closed by JanPetr** 2016-06-23 07:52 UTC
