### ISSUE TITLE
Using browser back button when on second page of category index displays all products

### ISSUE THREAD

**Issue by davidpike7** [algolia/algoliasearch-magento#360] opened 2016-04-20 01:31 UTC
Use the following steps to reproduce:

1. Visit https://www.schots.com.au/bathrooms/baths.html
2. Navigate to the second page of results
3. Hit back in browser 
4. Notice there are now 6150 results rather than 40

**Comment by maxiloc** [comment] 2016-04-25 12:32
@davidpike7 I managed to reproduce locally, we are working on a fix

**Comment by davidpike7** [comment] 2016-05-01 23:22
@maxiloc have you had any luck resolving this one?

**Comment by maxiloc** [comment] 2016-05-02 06:58
Yes we found out the root cause. The issue is actually in our instantsearch.js lib. We'll keep you updated.

**Comment by davidpike7** [comment] 2016-05-15 23:07
Hey @maxiloc just wondering if there has been any progress on this one? If not, do you have an ETA for a fix for this issue?

**Comment by maxiloc** [comment] 2016-05-15 23:17
Yes it has been fix in instantsearch.js repo. We are waiting for a release of instantsearch. We'll then update js dependencies of the extension. I don't have an ETA for now.

**Comment by davidpike7** [comment] 2016-05-15 23:28
Great thanks!

**Comment by maxiloc** [comment] 2016-05-17 09:43
Fixed with 77701fb.

It will be part of the next release you can update your js files in the meantime.

Thanks for reporting this.

**Closed by maxiloc** 2016-05-17 09:43 UTC
