### ISSUE TITLE
SQL Dump on Instant Search Results Page

### ISSUE THREAD

**Issue by MDowdal** [algolia/algoliasearch-magento#110] opened 2015-06-17 20:55 UTC
http://www.airfiltersdelivered.com/catalogsearch/result/?q=19%201/2%20x%2024%20x%201/2&instant=1#q=19%201/2%20x%2024%20x%201/2&page=0&refinements=[]&numerics_refinements={}&index_name=%22magentonew_afd_products%22 results in the following output:

object(PDOStatement)#568 (1) {
  ["queryString"] => string(1324) "SELECT DISTINCT `e`.`attribute_set_id` FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '2' AND price_index.customer_group_id = 0
 INNER JOIN `catalog_category_product_index` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id='2' AND cat_index.visibility IN(3, 4) AND cat_index.category_id='36'
 LEFT JOIN `catalog_product_entity_varchar` AS `at_name_default` ON (`at_name_default`.`entity_id` = `e`.`entity_id`) AND (`at_name_default`.`attribute_id` = '71') AND `at_name_default`.`store_id` = 0
 LEFT JOIN `catalog_product_entity_varchar` AS `at_name` ON (`at_name`.`entity_id` = `e`.`entity_id`) AND (`at_name`.`attribute_id` = '71') AND (`at_name`.`store_id` = 2)
 INNER JOIN `cataloginventory_stock_item` AS `at_inventory_in_stock` ON (at_inventory_in_stock.`product_id`=e.entity_id) AND ((at_inventory_in_stock.use_config_manage_stock = 0 AND at_inventory_in_stock.manage_stock=1 AND at_inventory_in_stock.is_in_stock=1) OR (at_inventory_in_stock.use_config_manage_stock = 0 AND at_inventory_in_stock.manage_stock=0) OR (at_inventory_in_stock.use_config_manage_stock = 1)) WHERE (e.entity_id IN (883, 1471, 10533, 11765, 5420, 10532, 11148, 11764, 5419, 11149)) ORDER BY `name` asc"
}

**Comment by maxiloc** [comment] 2015-06-17 21:05
Hi. We just released the new version of the plugin. Can you update and try if you still have this issue. This should be fixed. Check your settings save them and reindex your data to avoid conflicts with the previous version.

**Comment by MDowdal** [comment] 2015-06-17 21:11
I actually just updated to the magento connect version and am triggering the issue.

 

Micheal Dowdal

Lead Developer

Con-Air Industries

Office: 321-888-4046

Mobile: 321-304-7324

**Comment by MDowdal** [comment] 2015-06-17 21:19
Seems like it's still creating an issue with catalogsearch index.  Has been running for over 40 minutes now.

**Comment by maxiloc** [comment] 2015-06-17 21:33
@MDowdal Can you try to investigate, to see where it comes from. I am not able to reproduce it.

**Comment by maxiloc** [comment] 2015-06-17 21:33
I am not sure it is related to the plugin

**Comment by MDowdal** [comment] 2015-06-17 21:35
I've been having issues with catalogsearch since 1.1.14 came out, which I had opened under issue 90.  My catalogsearch index has taken inordinate amounts of time and creates a crash page when attempting to use catalogsearch during index.

**Comment by maxiloc** [comment] 2015-06-17 21:37
Yes but it is not supposed to index anymore. Since we replace catalogsearch by algolia

**Comment by maxiloc** [comment] 2015-06-17 21:37
Will investigate tomorrow. If you find anything please tell me.

**Comment by MDowdal** [comment] 2015-06-17 21:38
I'm running a manual reindex to see if that clears anything and will update you tomorrow if I'm still seeing it.

**Comment by MDowdal** [comment] 2015-06-18 13:58
Unfortunately we're still experiencing this issue.  Can you please advise?

**Comment by maxiloc** [comment] 2015-06-18 14:01
Can you come on the live chat so that we can debug the issue ?

**Comment by MDowdal** [comment] 2015-06-18 14:04
The catalogsearch index took roughly 8 hours to complete.  How do I get on the live chat?

**Comment by maxiloc** [comment] 2015-06-18 14:06
You come on https://algolia.com you will have a "Need help" button in the right bottom corner. And then Chat with us

**Comment by MDowdal** [comment] 2015-06-18 14:20
Can't at this moment.  However after installing the new version I've been getting Javascript errors on my site:

TypeError: $.noConflict is not a function
http://www.airfiltersdelivered.com:2209

SyntaxError: Unexpected token &
http://www.airfiltersdelivered.com:2693

[Algolia] Invalid instant-search selector: .main
http://www.airfiltersdelivered.com:994

Would appreciate if you could come take a look.  It's breaking parts of my site.

**Comment by MDowdal** [comment] 2015-06-18 14:20
SyntaxError: Unexpected token &
http://www.factorydirectfilters.com:5685

**Comment by MDowdal** [comment] 2015-06-18 14:24
Here's what I get on a product page:

ReferenceError: WOW is not defined
http://www.factorydirectfilters.com/ge-fqropf-reverse-osmosis-filter.html:105

TypeError: accordion is not a function
http://www.factorydirectfilters.com/ge-fqropf-reverse-osmosis-filter.html:4160

TypeError: accordion is not a function
http://www.factorydirectfilters.com/ge-fqropf-reverse-osmosis-filter.html:4173

TypeError: Cannot read property 'addSlideshow' of undefined
http://www.factorydirectfilters.com/ge-fqropf-reverse-osmosis-filter.html:4254

TypeError: undefined is not a function
http://www.factorydirectfilters.com/ge-fqropf-reverse-osmosis-filter.html:4963

TypeError: BlockToggler is not a function
http://www.factorydirectfilters.com/ge-fqropf-reverse-osmosis-filter.html:5395

TypeError: BlockToggler is not a function
http://www.factorydirectfilters.com/ge-fqropf-reverse-osmosis-filter.html:5424

ReferenceError: algoliasearch is not defined
http://www.factorydirectfilters.com/ge-fqropf-reverse-osmosis-filter.html:505

TypeError: navPro is not a function
http://www.factorydirectfilters.com/ge-fqropf-reverse-osmosis-filter.html:4152

TypeError: $ is not a function
http://www.factorydirectfilters.com/ge-fqropf-reverse-osmosis-filter.html:4170

TypeError: MobileNavigation is not a function
http://www.factorydirectfilters.com/ge-fqropf-reverse-osmosis-filter.html:4181

TypeError: undefined is not a function
http://www.factorydirectfilters.com/ge-fqropf-reverse-osmosis-filter.html:5299

ReferenceError: AjaxPro is not defined
http://www.factorydirectfilters.com/ge-fqropf-reverse-osmosis-filter.html:5240

TypeError: undefined is not a function
http://www.factorydirectfilters.com/ge-fqropf-reverse-osmosis-filter.html:5299

TypeError: Cannot set property 'graphicsDir' of undefined
http://www.factorydirectfilters.com/ge-fqropf-reverse-osmosis-filter.html:5328

**Comment by maxiloc** [comment] 2015-06-18 14:26
[Algolia] Invalid instant-search selector: .main
This one means that instant search is enable and you have a bad selector for it. You probably want to use #content instead you can modify it in System > Configuration > AlgoliaSearch > Instant Search Results Page Configuration > DOM Selector

**Comment by MDowdal** [comment] 2015-06-18 14:29
[Algolia] Invalid instant-search selector: #content
 <view-source:http://www.factorydirectfilters.com/> http://www.factorydirectfilters.com:967

 

 

Micheal Dowdal

Lead Developer

Con-Air Industries

Office: 321-888-4046

Mobile: 321-304-7324

**Comment by maxiloc** [comment] 2015-06-18 14:29
It looks like you don't have any assets loaded (css/js). Can you check ?

**Comment by MDowdal** [comment] 2015-06-18 14:31
All the assets are loaded through the Magento connect extension.  This behavior did not start happening until we updated.

**Comment by MDowdal** [comment] 2015-06-18 14:33
I just uninstalled through Magento Connect and everything is working fine now.  The issue was the new Algolia search.

**Comment by MDowdal** [comment] 2015-06-18 14:35
Even better, removing Algolia no longer results in the crash page when I pull up catalogsearch at http://www.factorydirectfilters.com/catalogsearch/result/?q=25+x+25+x+1 or http://www.airfiltersdelivered.com/catalogsearch/result/?q=17+x+85.

We really want to make use of this extension.  Would appreciate it if you could help debug it.

**Comment by maxiloc** [comment] 2015-06-18 14:36
Can you come chat here https://www.hipchat.com/gmaN3Z4cx. Github is not the best place for that

**Comment by MDowdal** [comment] 2015-06-19 16:41
Just did an update to 1.2.2 and still having the same issue.

**Comment by maxiloc** [comment] 2015-06-19 16:48
Ok I will check that later today. It is on the staging server. Right ?

**Comment by MDowdal** [comment] 2015-06-19 16:52
Yep, http://upgrade.factorydirectfilters.com/ge-fqropf-reverse-osmosis-filter.html

 

Micheal Dowdal

Lead Developer

Con-Air Industries

Office: 321-888-4046

Mobile: 321-304-7324

**Comment by maxiloc** [comment] 2015-06-19 22:08
@MDowdal Yes so it is not related to the extension directly. You need to find the code bellow that is not part of the extension add a semi colon at the end. This will fix javascript errors. Do not forget to recompact the js. So that the ';' is also present in the compact file

````
var fileUploaderPopup = {
    open: function(options)
    {
        this.options = {
            url: '#',
            width: 600,
            height: 500,
            name:"_blank",
            location:"no",
            menubar:"no",
            toolbar:"no",
            status:"yes",
            scrollbars:"yes",
            resizable:"yes",
            left:"",
            top:"",
            normal:false
        }
        Object.extend(this.options, options || {});

        if (this.options.normal){
            this.options.menubar = "yes";
            this.options.status = "yes";
            this.options.toolbar = "yes";
            this.options.location = "yes";
        }

        this.options.width = this.options.width < screen.availWidth?this.options.width:screen.availWidth;
        this.options.height=this.options.height < screen.availHeight?this.options.height:screen.availHeight;
        var openoptions = 'width='+this.options.width+',height='+this.options.height+',location='+this.options.location+',menubar='+this.options.menubar+',toolbar='+this.options.toolbar+',scrollbars='+this.options.scrollbars+',resizable='+this.options.resizable+',status='+this.options.status
        if (this.options.top!="")openoptions+=",top="+this.options.top;
        if (this.options.left!="")openoptions+=",left="+this.options.left;
        window.open(this.options.url, this.options.name,openoptions );
        return false;
    }
}
```

**Closed by maxiloc** 2015-06-19 22:08 UTC

**Comment by MDowdal** [comment] 2015-06-22 18:08
That javascript error makes the product page work but I still have the crash on catalogsearch.

**Comment by MDowdal** [comment] 2015-06-22 18:53
I was able to get the catalogsearch crash to happen on my live site, but not able to reproduce on staging.  Also, when installed to my live site it duplicated the NIVOSlider on the homepage of airfiltersdelivered.com.  Very strange.

**Comment by muyayo** [comment] 2015-06-22 19:02
.

**Comment by maxiloc** [comment] 2015-06-23 08:58
@MDowdal Can you try to run the mysql command on the dump. And check if there is an error.

For the slider, it not probably not related to the extension. It seems you have javascript error, can you try to fix it first.

**Comment by MDowdal** [comment] 2015-06-23 15:47
I can run the SQL query and get the same error on Upgrade's database where the catalogsearch crash doesn't happen.  Last week when I removed alogolia completely the issue disappeared as well, and only reoccurs after reinstalling algolia.

**Comment by MDowdal** [comment] 2015-06-23 16:31
Okay, now I've finally gotten catalogsearch to stop crashing.  No idea why, because I didn't change or remove any other extensions - just required several reindexes of catalogsearch.

**Comment by MDowdal** [comment] 2015-06-23 16:32
Should I disable indexing of catalogsearch when I install Algolia in the future?  Or in any other way attempt to disable catalogsearch?

**Comment by maxiloc** [comment] 2015-06-23 17:14
Ok. Cool that the issue is fix (kind of). No idea why either :smile: . Yes you can definitely disable magento catalogsearch indexing because the Algolia indexer should replace it totally.

I am thinking of a way to avoid this issue permanently. Need to discuss it with the team

**Comment by MDowdal** [comment] 2015-06-23 17:21
Thanks.  I do find it strange that the issue is not occuring on the staging instance.  Need to check a couple of configurations.
