### ISSUE TITLE
algoliasearch_queue filling up with rebuildCategoryIndex rows

### ISSUE THREAD

**Issue by bslinger** [algolia/algoliasearch-magento#555] opened 2016-08-22 01:43 UTC
We upgraded to the 1.7.0 release candidate last week, and of course did a full reindex of all indices after installation. Since then, however, the algoliasearch_queue table has never managed to empty, and the rebuildCategoryIndex rows just keep growing. We've reached 50% of our Algolia operations quota for the month because we hadn't realised it was indexing all weekend.

Any idea how we could resolve this? I've been clearing out the rebuildCategoryIndex so that our products get reindexed correctly, as that's more important to us, but we're going to hit out operations cap in a few days at this rate.

Please let me know what information you need to help resolve!

**Comment by JanPetr** [comment] 2016-08-22 07:42
Hello @bslinger,
thanks for reporting, unfortunatelly I cannot reproduce.

Few questions:
- From which version did you upgrade?
- Which version of Magento do you use?
- Does it happen only when you indexing categories? If you are indexing products/pages/... is doesn't add multiply `rebuildCategoryIndex` rows?
- Does it happen only on full category reindex or all the time even when you "normally" work with categories?
- Can you enable Algolia logging, clear log director, reindex and send me the log file?

Thanks for your help!

**Comment by bslinger** [comment] 2016-08-22 23:13
Hi @JanPetr ,

- We upgraded from 1.5.5
- Magento version 1.9.1.0
- I think it is adding new rebuildCategoryIndex rows when products are indexed, yes. I have been clearing out the rebuildCategoryIndex rows so that the queued product indexes can run, and new rebuildCategoryIndex rows start coming back immediately without me triggering a reindex.
- I haven't managed to clear out the whole algolisearch_queue table, but I haven't triggered a full index in days and there are 44000 new rebuildCategoryIndex rows in the last 18 hours.
- I'll do this for you now and attach the log file when it's done - we are now at 80% of our 10M records for the month though, do you know who we could talk to about getting a credit for the month, considering this is likely caused by a bug in the module?

**Comment by JanPetr** [comment] 2016-08-23 11:38
Thank for answers @bslinger,
can I as well ask you to printscreen your whole Algolia settings from Magento administration?
You can send the screenshots to support+magento@algolia.com so you don't have to share it here.

Thanks!

**Comment by JanPetr** [comment] 2016-08-23 11:49
I found most probably found the issue @bslinger! In new version the extension reindexes product's categories each time the product is saved (to keep correct product count etc. within categories in Algolia). Can you send me example (screenshot, SQL file, ...) of the `rebuildCategoryIndex` rows in your DB?

To stop that you can comment [these lines](https://github.com/algolia/algoliasearch-magento/blob/develop/app/code/community/Algolia/Algoliasearch/Model/Indexer/Algolia.php#L191-L193) out.

**Comment by bslinger** [comment] 2016-08-23 22:45
@JanPetr,

I've sent the email with our settings, and here are the gzipped logs from the reindex yesterday (algolia.log.1.gz is the earlier one) - it's not a complete log as, of course, the queue table is still not empty. (Currently 3135 rebuildCategoryIndex and 315 rebuildProductIndex)

I've also attached the data from the algoliasearch_queue table.

[algolia.log.1.gz](https://github.com/algolia/algoliasearch-magento/files/433692/algolia.log.1.gz)
[algolia.log.gz](https://github.com/algolia/algoliasearch-magento/files/433693/algolia.log.gz)
[algoliasearch_queue.sql.gz](https://github.com/algolia/algoliasearch-magento/files/433695/algoliasearch_queue.sql.gz)

I'll add some logging to those lines and see if I can determine which one is adding new rows to the table.

Also, we are now at 9.5 million out of our 10 million operations for the month, with 24 days left - are you able to organise a credit for us for this month?

**Comment by bslinger** [comment] 2016-08-23 23:03
Here are my log files generated over the last 20 minutes or so for every time events are added at the lines you specified - I've included a trace in case that helps as well.

[algolia_issue.log.gz](https://github.com/algolia/algoliasearch-magento/files/433726/algolia_issue.log.gz)

**Comment by JanPetr** [comment] 2016-08-24 08:06
Thank you very much @bslinger, the debug information are awesome!
Didn't you recently (sometime around Algolia update) add or change frequency of `cron.php` or `cron-erp.php`?
Because what I can see is that the vast majority of updates come from `cron-erp.php` which updates products' stock. And everytime the products' stock is updated the update of it's categories triggered to synchronize the right amount of products in the category (in case the product goes out of stock).
And when I compare the code between version 1.5.5 and 1.7.0 it works still the same.

Thanks for cooperation. I will see what I can do about the operation quota.

**Comment by bslinger** [comment] 2016-08-24 10:18
No, we haven't changed the frequency of any of our crons, they should be working the same way they always have. We are in a busier period so stock updates would be happening more often, but not enough that we should be using this many operations. 

I can see by looking at the diff of the Algolia module upgrade that they seem to work the same way (although you of course would be the expert on that, I don't fully understand the purpose of a lot of the indexing functions there), so I'm really not sure what could be happening here.

**Comment by JanPetr** [comment] 2016-08-24 11:49
That's really really weird. I cannot find another explanation. If you downgrade to 1.5.5 will it be OK? Can you try it?

**Comment by bslinger** [comment] 2016-08-29 00:30
Hi @JanPetr - I was on leave at the end of last week so unfortunately couldn't follow up on this further. This means of course that our operations have continued to blow out and we're not at nearly 17M for the month, so I'm hoping we can get this resolved.

Downgrading to 1.5.5 is not really an option at this point, as the backwards compatibility breaks will mean our search is broken while it reindexes, and we are in the busiest time of the year. Is there a workaround you could possibly give to prevent these additional operations being added to the queue in the meantime? We may be able to try downgrading at a later date once we're not so busy.

**Comment by rayrutjes** [comment] 2016-08-29 08:33
Hi @bslinger, @JanPetr is unfortunately off for a few days but I can tell that if the plugin causes somehow an infinite loop somewhere, I'm sure we will find a solution about the overquota ;)

Please bear with us a couple of days until Jan is back!

**Comment by JanPetr** [comment] 2016-09-07 11:15
Hello @bslinger,
you can comment this out: https://github.com/algolia/algoliasearch-magento/blob/develop/app/code/community/Algolia/Algoliasearch/Model/Indexer/Algolia.php#L191-L193
It should stop creating so many category jobs.

**Comment by bslinger** [comment] 2016-09-08 00:31
Thanks @JanPetr, I'll try that. Is this a permanent fix, or are we losing some functionality with this change?

**Comment by bslinger** [comment] 2016-09-12 02:02
Looks like it's had the desired effect, are you able to answer my previous question about functionality? And if we can organize a credit to our account for the additional operations this month, that would be great.

![screenshot-www algolia com 2016-09-12 12-00-16](https://cloud.githubusercontent.com/assets/603386/18422601/9a6d91b6-78e0-11e6-937c-f6507ba1ed62.png)

**Comment by JanPetr** [comment] 2016-09-12 07:44
Hello @bslinger,
I'm sorry for the delay.

Yes, right now you've lost functionality which ensures that `product_count` attribute within categories is always correct and some categories may become empty but will still appear in results.

I contacted my colleague about your overquota and he'll take care of it :)

**Comment by bslinger** [comment] 2016-09-12 12:44
Thanks so much for your help, and for the update.

Are there any workarounds for losing that functionality? Can I run the algolia_search_indexer_cat indexer regularly to keep it up to date?

And let me know if there's any more help I can give in tracking down the issue - I know it's a tricky one as we have a complex environment so it may be an odd interaction somewhere.

**Comment by JanPetr** [comment] 2016-09-12 12:48
Yes, you can definitelly run category reindexation on regular basis. It will keep the categories index in sync.

I really tried to find the cause of the issue and cannot find anything. It'd really help me if you could downgrade to 1.5.5 (or the version where you didn't experice the issue) and see if it's OK or if the issue is still present. Because the code should be the same ...

Thank you for your cooperation.

**Comment by JanPetr** [comment] 2016-10-18 09:27
Hello @bslinger,
do you have any updates on the issue? Did you manage to sort it out?

Let me know please.

**Comment by JanPetr** [comment] 2016-10-26 15:06
Hello @bslinger,
I'll close the issue now. If you're still experiencing the issue, feel free to reopen.

**Closed by JanPetr** 2016-10-26 15:06 UTC
Labels: investigate, major
